### ISSUE TITLE
[Frontend] Drawing single dot not supported

### ISSUE THREAD

**Issue by m-hofmann** [alxwdm/doodle-devops#6]
Observed behavior: When I want to draw a single dot by just clicking on the canvas, nothing is drawn. I have to move the mouse cursor to draw a line. 

Expected behavior: Just clicking draws a single, round dot.

**Comment by alxwdm** [comment]
Thank you for your contribution - I am looking into it.
However, I don't think that this can be solved without major changes since the canvas depends on [embiem/react-canvas-draw](https://github.com/embiem/react-canvas-draw), which in turn uses [dulnan/lazy-brush](https://github.com/dulnan/lazy-brush). I have already set `lazyRadius: 0`, but I guess the described behavior is considered to be a feature of lazy-brush.
